travis:
  secure:
    BINSTAR_TOKEN: e3IYCZRBNTUhcHBImAKd9qMyaLCNBGHzeG2dd4iLGAQmRJqBLUNwhH2IMWbrin6zs12VipwxZtgKBBWLWo4IW43a8bkRz9xkEPyLtGTcqj3K+wSeOC0CNB/Vqq7tAD/CmJw6M3MkinZzVDG6zXrVw7v2O1gxYWSBqhgqG7PvLlJG6URRa8XGLvjCQfEY8l/SpolnOvGE4b4g4Rxny60rLdCdBvOSAtqrK8VWPk9KQClediUoAG9ie+WzBCPTHOAWo+bWTKPIb1VCh0ttPJBkfTN7lbxWn2wD8OUues7/2VbGWC7/TCuxLK8ZMFwtVSBRfm5LdwFLaQWS7VNe3PhrCdayHmwLBoNPogRTLa8otHlK/+ISyl+FihpqFz1HzXZ5vfbwVnL1+h1JbgIX/B1ElbuhKGH6inb6zoYL6bVMB3he5hrXqjWl/dG6BiUXUURiVRqAp2Aosz38lhGwUrIFA/pLAz0FcyQRuuh2RMOb6sf5AFhXOLobQfYab8q2/KCe7Kl5Bdmto7uiZ0CSkEQKYiWHP0EJRTzxMBPuQ1OySsVRj1B1gr8J8xO8ULR8zHIrtKPal8XbqDvqOqMMnrPnlgM+F6YB/CVVLepUPmQ5E9EDXVPYt0gK4sjSQ+w2jsPX8FSWek49/JI/PCm2K3JTlOdnB8LAQCy/PA0BkOjBNR0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
