travis:
  secure:
    BINSTAR_TOKEN: DtMZ/qhDmfbrLNIB+v8i1dQZFDPehGDNdc6cDRGVWMwDOsZzX2QV7BA5Zci9LMLr3KMMb899j+U879no0VYtt2J7l9lRrpmkmw3NHdIYyO6w/HEEI8jvDjpIhBfwqQX95Qv6Ns09Mv/b+6+Zgx6taiIXKP4Y46BQdoU1wnwn/TeOScWJc1PlFsJz9MzFP+TTxLRqypmFj2JU4DhOjovXLexhObwnSNSq6SfpUP0Ci3OQ5cRMeEee7jsPDxFb/eoseqFuCC1kl/Z8i0bdzIn7ZSgLpsfb5jF8mWMdJsSBARKjyvrqQmM47TOWAjFBBLOiByKbp7i3vQ4hW7qvxSagqfcPr5ISh0nBfhp4NsxYkesCIib6it8dcRYlcSiMx9mRKhuhx1kQQtMeeUUGorSbet1Rw86V9JtEeu8b384+kt4502dD8wNIvGA2PhioGYWrk92V31D9F+UhYxcHTRVDMHSG3q1RxjQMdBOV1tihFJAYwyVWXdFUZQ/QKvSMDNFVUCKrrEnWY7ZC/fFm1PR/kWkWnWm4P1Ep1DGoF/rQeR4FZcaZFJOx281FL03QKBmp9p7WTKgCYR8H1YQ5sNfgSzdR9tjYPkQhlwqLvBF7iAUvGFBk6oUgj7WqeoGO0R0yb9I1zL7PHhQWl1Sq1Gr2OlSbXYoVxR2f2+uvUEac9jo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
